### ISSUE TITLE
Build fails with vue webpack template

### ISSUE THREAD

**Issue by tomsseisums** [drenglish/vue-match-media#2]
Using vue webpack template.

Everything runs smooth when I am in development mode running webpack dev server, but when I am building the source, I receive:

    ERROR in static/js/vendor.f79cb26a06466bc8000a.js from UglifyJs
    Invalid assignment [./~/vue-match-media/src/index.js:7,0]
    [static/js/vendor.f79cb26a06466bc8000a.js:19702,72]

Including by:
    
    import MQ from 'vue-match-media/src'
    Vue.use(MQ)

**Comment by jeshtan** [comment]
Hi @joltmode, I encounter this issue when compiling codes. Did you find solution for this?

**Comment by tomsseisums** [comment]
Umm, well, yeah, but I don't like it.

I'm not using the module version, I cloned the repo instead and imported code from there.

In order for it to work, I had to include Flow support for my webpack. I first found this guide: https://alligator.io/vuejs/components-flow/

From there I found to add the following NPM modules: `babel-plugin-syntax-flow`, `babel-plugin-transform-class-properties`, `babel-plugin-transform-flow-strip-types`.

Next up, I added them to `.babelrc` `plugins` field.

I skipped the `.eslintrc` configuration, because I do not care for it if I'm using Flow only for this plugin.

And lastly, I created the empty `.flowconfig`.

That enabled it to build smoothly.

**Comment by drenglish** [comment]
Hi -- apologies for my lack of response; Github notifications were going to spam, I'm afraid, and past that life has kept me busy elsewhere.

You mention cloning the repo -- did you do that because you were having trouble with the NPM package? As of the last release, on July 19 (1.0.2), the NPM package no longer ships with any build artifacts, and there aren't any Flow annotations there anymore either. (It was silly to release with that stuff there in the first place, but I'm new to putting out public libraries.)

Likewise, package.json has a "main" field that points to the ES5 distributable, and afaik if you're using that there shouldn't be any module issues requiring workarounds.

I don't use webpack in my own build workflow and don't have any real experience hacking webpack problems, but if the latest version of the plugin is causing problems with it I'll dig in and see what I can do to fix.

**Comment by jeshtan** [comment]
Hi @drenglish, thanks for the hint. I finally solve out this issue by manually aliases this package resolve to `dist/index.js`. It seem webpack2 will import ES6 module version directly if package.json file has a module field. However, UglifyJs doesn't understand ES6 syntax and that's why we got the `invalid assignment` error when building source.

Thanks for this great plugin anyway!

**Comment by drenglish** [comment]
Funny - I just now learned on another thread that webpack 2/3 will read the module field; that's how little I know webpack.

Like you, I've beaten my head against the uglify problem; I had to remove it from my Rollup workflow entirely and use it directly in my NPM scripts. Someday ES6 code will just work everywhere. That'll be nice.

Glad the plugin is useful, in spite of build issues.

**Comment by tomsseisums** [comment]
Yes, I had trouble with the NPM package. 
Since in development mode I got a taste of this plugin, I sought out for solutions and sticked with cloning. 

I kept following the project and once the latest release dropped, I thought that it would have fixed the issue, but that didn't work either. That's when I reported the issue (July 27).

It seems that you have found a hint on how to fix it. Looking forward to release. :+1:
