### ISSUE TITLE
format 'umd' instead of es6?

### ISSUE THREAD

**Issue by prograhammer** [drenglish/vue-match-media#4]
I was curious about the `format: 'umd'` in rollup config (and the `babelrc: false` when you have an existing `.babelrc` in the project). I was interested because I wanted to use the package in my own library using rollup. Maybe I am misunderstanding something. I thought that typically a umd release would be transpiled to `pkg.main` (`/dist/index.js`) and an es6 module (also transpiled) would be in `pkg.module` (maybe `/dist/index.es.js` or something).

**Comment by prograhammer** [comment]
As a reference, here's a project's config from a project of the rollup creator himself: https://github.com/Rich-Harris/magic-string/blob/master/rollup.config.js

**Comment by drenglish** [comment]
The package.json for this plugin has a "main" field that points to the ES5 distributable (dist/index.js) and a "module" field that points to src/index.js. Since the ES6 source is a single file, with no other dependencies (except Vue, which is just a peer dependency), there isn't anything else to bundle and so no output target for it in my rollup config.

I use rollup in my own build workflow, and since rollup understands the module field in package.json, there's no other configuration required to bundle the plugin into the larger codebase.

The .babelrc in the project is there for the sake of Jest, which needs it for its own transpile step before running tests. I'm using the "env" preset there and in rollup.config, but with different settings, so for rollup I ignore .babelrc and just specify the preset options in the plugin.

**Comment by prograhammer** [comment]
Ahh. Gotcha. Also, you could use Webpack 2/3 at your app level as it will also automatically grab your ES6 module (defined in your package.json module field) from your supporting libraries you built with Rollup. Thanks for clarification!
